import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { publishChromePackage } from '../scripts/chrome-webstore-publish.mjs';
import { uploadAndValidateAmo, validateAmoConfiguration } from '../scripts/amo-upload.mjs';

const workflow = readFileSync(new URL('../.github/workflows/release-extension.yml', import.meta.url), 'utf8');
const chromeScript = readFileSync(new URL('../scripts/chrome-webstore-publish.mjs', import.meta.url), 'utf8');
assert.match(workflow, /chrome-publish:/); assert.match(workflow, /needs: chrome-upload/);
assert.match(workflow, /inputs\.store-publish-enabled == 'true'/); assert.match(workflow, /vars\.STORE_PUBLISH_ENABLED == 'true'/);
const amoScript = readFileSync(new URL('../scripts/amo-upload.mjs', import.meta.url), 'utf8');
assert.match(chromeScript, /:publish/); assert.match(amoScript, /BASE.*addons/);
let calls = [];
const fetchOk = async (url, options) => { calls.push({ url, options }); return { ok: true, json: async () => ({}) }; };
await assert.rejects(publishChromePackage({ publisher: '', extensionId: '', token: '', fetchImpl: fetchOk })); assert.equal(calls.length, 0);
await publishChromePackage({ publisher: 'p', extensionId: 'e', token: 't', fetchImpl: fetchOk }); assert.equal(calls.at(-1).url, 'https://chromewebstore.googleapis.com/v2/publishers/p/items/e:publish');
calls = [];
const fixture = join(mkdtempSync(join(tmpdir(), 'amo-test-')), 'extension.zip'); writeFileSync(fixture, 'zip');
assert.deepEqual(validateAmoConfiguration({ uploadEnabled: 'false', publishEnabled: 'false', addonId: '', issuer: '', secret: '' }), { enabled: false });
await assert.rejects(uploadAndValidateAmo({ zipPath: fixture, addonId: '', jwt: '', fetchImpl: fetchOk })); assert.equal(calls.length, 0);
calls = [];
const amoFetch = async (url, options) => { calls.push({ url, options }); if (url.endsWith('/upload/')) return { ok: true, json: async () => ({ uuid: 'u' }) }; return { ok: true, json: async () => ({ processed: true, valid: true }) }; };
await uploadAndValidateAmo({ zipPath: fixture, addonId: 'a', jwt: 't', fetchImpl: amoFetch, submit: false }); assert.equal(calls.length, 2);
await uploadAndValidateAmo({ zipPath: fixture, addonId: 'a', jwt: 't', fetchImpl: amoFetch, submit: true }); assert.equal(calls.length, 5); assert.match(calls.at(-1).url, /versions\/$/);
const invalid = async (url) => { calls.push(url); return url.endsWith('/upload/') ? { ok: true, json: async () => ({ uuid: 'u' }) } : { ok: true, json: async () => ({ processed: true, valid: false }) }; };
calls = []; await assert.rejects(uploadAndValidateAmo({ zipPath: fixture, addonId: 'a', jwt: 't', fetchImpl: invalid, submit: true })); assert.equal(calls.length, 2);
console.log('store publish and AMO fail-closed mock tests passed');
